<!-- Mirrored from crane.grooni.com/f-a-q/ by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 20 Oct 2018 18:52:29 GMT -->
<!-- Added by HTTrack -->
<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
<!-- /Added by HTTrack -->
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="profile" href="http://gmpg.org/xfn/11">
<link rel="pingback" href="xmlrpc.php">
<title>F.A.Q. &#8211; The Crane</title>
<script type="text/javascript">
		var ajaxurl = 'wp-admin/admin-ajax.html';
		</script>
<link rel='dns-prefetch' href='index.html' />
<link rel='dns-prefetch' href='http://fonts.googleapis.com/' />
<link rel='dns-prefetch' href='http://s.w.org/' />
<link rel="alternate" type="application/rss+xml" title="The Crane &raquo; Feed" href="feed/index.html" />
<link rel="alternate" type="application/rss+xml" title="The Crane &raquo; Comments Feed" href="comments/feed/index.html" />
<script>
	
// if (window.top.location != document.location) {
//     window.top.location.href = document.location.href;
// }

</script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-120002447-1"></script>
<style type="text/css">
img.wp-smiley, img.emoji {
	display: inline !important;
	border: none !important;
	box-shadow: none !important;
	height: 1em !important;
	width: 1em !important;
	margin: 0 .07em !important;
	vertical-align: -0.1em !important;
	background: none !important;
	padding: 0 !important;
}
</style>
<link rel='stylesheet' id='contact-form-7-css'  href='wp-content/plugins/contact-form-7/includes/css/styles5560.css?ver=5.0.4' type='text/css' media='all' />
<link rel='stylesheet' id='groovy-menu-style-css'  href='wp-content/plugins/groovy-menu/assets/style/frontend4e44.css?ver=1.3' type='text/css' media='all' />
<link rel='stylesheet' id='groovy-menu-style-fonts-groovy-28328-css'  href='wp-content/uploads/groovy/fonts/groovy-283284e44.css?ver=1.3' type='text/css' media='all' />
<link rel='stylesheet' id='groovy-menu-style-fonts-groovy-69018-css'  href='wp-content/uploads/groovy/fonts/groovy-690184e44.css?ver=1.3' type='text/css' media='all' />
<style id='woocommerce-inline-inline-css' type='text/css'>
.woocommerce form .form-row .required {
	visibility: visible;
}
</style>
<link rel='stylesheet' id='bsf-Defaults-css'  href='wp-content/uploads/smile_fonts/Defaults/Defaults5010.css?ver=4.9.8' type='text/css' media='all' />
<link rel='stylesheet' id='bsf-wp-Ingenicons-css'  href='wp-content/uploads/smile_fonts/wp-Ingenicons/wp-Ingenicons5010.css?ver=4.9.8' type='text/css' media='all' />
<link rel='stylesheet' id='ultimate-style-min-css'  href='wp-content/plugins/Ultimate_VC_Addons/assets/min-css/ultimate.min957f.css?ver=3.16.25' type='text/css' media='all' />
<link rel='stylesheet' id='js_composer_front-css'  href='wp-content/plugins/js_composer/assets/css/js_composer.min7e15.css?ver=5.5.4' type='text/css' media='all' />
<link rel='stylesheet' id='js_composer_custom_css-css'  href='wp-content/uploads/js_composer/custom7e15.css?ver=5.5.4' type='text/css' media='all' />
<link rel='stylesheet' id='crane-style-css'  href='wp-content/themes/crane/style79cd.css?ver=1.3.7.1' type='text/css' media='all' />
<link rel='stylesheet' id='crane-style-main-css'  href='wp-content/themes/crane/assets/css/style-main.min79cd.css?ver=1.3.7.1' type='text/css' media='all' />


<link rel='stylesheet' id='crane-style-css'  href='bootstrap.css' type='text/css' media='all' />
<link rel='stylesheet' href='style.css' type='text/css'/>
<link rel='stylesheet' id='crane-style-css'  href='custom.css' type='text/css' media='all' />


<style id='crane-style-main-inline-css' type='text/css'>
/* Custom style from admin panel. Please, DO NOT edit this file, because it updates automatically. */

.crane-page-title {
	height: 200px;
}
.crane-page-title-heading, .crane-page-title-holder {
	font-family: "Open Sans";
	text-transform: uppercase;
	font-weight: 400;
	font-style: normal;
	color: #000000;
	font-size: 37px;
}
.crane-page-title {
	background-color: #f9f9f9;
}
.crane-page-title {
	border-bottom: 1px solid #eaeaea;
}
.crane-breadcrumb {
	font-family: "Open Sans";
	text-transform: uppercase;
	font-weight: 600;
	font-style: normal;
	color: #4d4d4d;
	font-size: 12px;
}
.crane-breadcrumb-nav__item+.crane-breadcrumb-nav__item::before {
	color: #b9b9b9;
}
body {
	font-family: "Open Sans";
	text-transform: initial;
	font-weight: 400;
	font-style: normal;
	font-size: 14px;
}
h1 {
	font-family: "Open Sans";
	text-transform: initial;
	font-weight: 600;
	font-style: normal;
	font-size: 34px;
}
h2 {
	font-family: "Open Sans";
	text-transform: initial;
	font-weight: 700;
	font-style: normal;
	font-size: 31px;
}
h3 {
	font-family: "Open Sans";
	text-transform: initial;
	font-weight: 700;
	font-style: normal;
	font-size: 23px;
}
h4 {
	font-family: "Open Sans";
	text-transform: initial;
	font-weight: 400;
	font-style: normal;
	font-size: 20px;
}
h5 {
	font-family: "Open Sans";
	text-transform: initial;
	font-weight: 700;
	font-style: normal;
	font-size: 17px;
}
h6 {
	font-family: "Open Sans";
	text-transform: initial;
	font-weight: 700;
	font-style: normal;
	font-size: 15px;
}
.woocommerce-tabs .tabs>li.active,  .woocommerce .products .price,  .crane-portfolio-style-modern .portfolio-filters-btn.active,  .comment-metadata .comment-author {
	color: #93cb52;
}
.crane-portfolio-style-flat .portfolio-filters-btn.active,  .crane-portfolio-style-minimal .portfolio-filters-btn.active,  blockquote {
	border-color: #93cb52;
}
.woocommerce-tabs .tabs>li.active::after {
	border-top-color: #93cb52;
}
blockquote:not(.crane-blockquote-main):not(.wp-block-pullquote) {
	border-left-color: #93cb52;
}
button,  .button,  .wp-block-button__link,  input[type="submit"],  .comment-button-group a:hover,  .btn,  .select2-container--default .select2-results__option--highlighted[aria-selected],  .select2-results .select2-highlighted,  .dark-btn:hover,  .primary-btn,  input[type="button"]:hover,  input[type="reset"]:hover,  input[type="submit"]:hover,  .woocommerce span.onsale,  .woocommerce-tabs .tabs>li.active::before,  .woocommerce .add_to_cart:hover,  .ui-slider-horizontal .ui-slider-range,  .carousel .x,  .carousel .y,  .page-numbers:not(.dots):hover,  .navigation .nav-previous a:hover,  .navigation .nav-next a:hover,  .page-numbers.current,  .blog-inner .page-links > span,  .format-quote .crane-blog-header,  .post__blockquote .crane-blockquote-main,  .crane-blog-layout-cell .crane-blog-grid-meta .crane-blog-grid-meta__title::after,  .crane-search-title::after,  .product-card__tabs__nav__item.active > .product-card__tabs__nav__item__link::before,  .crane-info-box,  .footer-type-dark .widget-title::after,  .instagram-pics li a::before,  .footer-type-light .widget-title::after {
	background-color: #93cb52;
}
.woocommerce .star-rating span,  .woocommerce p.stars a:hover {
	color: #fab710;
}
.crane-content {
	background-color: #ffffff;
}
.crane-content > .crane-breadcrumb,  .search-results article,  .select2-results,  code,  pre:not(.wp-block-verse) {
	background-color: #fbfbfb;
}
h1, h2, h3, h4, h5, h6 {
	color: #686868;
}
body {
	color: #686868;
}
a {
	color: #85bf43;
}
a:hover {
	color: #6eb238;
}
a:active {
	color: #85bf43;
}
.crane-content > .crane-breadcrumb,  input[type="text"],  input[type="password"],  input[type="email"],  input[type="url"],  input[type="tel"],  input[type="number"],  input[type="date"],  input[type="search"],  textarea,  select,  .wp-embed,  .woocommerce-product-details__short-description,  .woocommerce-tabs .tabs,  .woocommerce #reviews #comments ol.commentlist li .comment-text,  .woocommerce .order_details li:not(:last-of-type),  .woocommerce-checkout .shop_table tr,  .order-received-wrapper .order_item,  .select2-container--default .select2-selection--single,  .select2-dropdown,  .select2-container .select2-choice,  .select2-drop-active,  .post-divider,  hr,  th,  td,  code,  pre,  .crane-re-comments__item,  .crane-re-posts__item,  .widget .cat-item,  .widget .menu-item,  .crane-archive-widget li,  .cat-item .children,  .widget .menu-item .children,  body:not(.woocommerce) .comment,  body:not(.woocommerce) .pingback,  .crane-blog-style-flat .crane-blog-grid-meta__wrapper:not(:only-child),  .portfolio-filters-group,  .portfolio__aside,  .product-inner,  .crane-portfolio__meta--border::after,  .crane-portfolio-grid-meta .crane-portfolio-inliner:not(:only-child) {
	border-color: #dbdbdb;
}
.ui-slider-horizontal::before {
	background-color: #dbdbdb;
}
input[type="text"]:focus,  input[type="password"]:focus,  input[type="email"]:focus,  input[type="url"]:focus,  input[type="tel"]:focus,  input[type="number"]:focus,  input[type="date"]:focus,  input[type="search"]:focus,  textarea:focus,  select:focus,  .select2-container--default.select2-container--focus .select2-selection--single {
	border-color: #c5c5c5;
}
.crane-regular-page .crane-content-inner, .crane-regular-page .crane-sidebar {
	padding-top: 80px;
	padding-bottom: 80px;
}
.crane-portfolio-archive .crane-content-inner, .crane-portfolio-archive .crane-sidebar {
	padding-top: 80px;
	padding-bottom: 80px;
}
.crane-portfolio-single .crane-content-inner, .crane-portfolio-single .crane-sidebar {
	padding-top: 80px;
	padding-bottom: 80px;
}
.crane-blog-archive .crane-content-inner, .crane-blog-archive .crane-sidebar {
	padding-top: 80px;
	padding-bottom: 80px;
}
.crane-blog-archive-layout-cell .crane-blog-layout-cell .crane-blog-grid-meta {
	background-color: #f8f7f5;
}
.crane-blog-archive-layout-cell .crane-blog-layout-cell .crane-blog-grid-meta {
	border-color: #f8f7f5;
}
.crane-blog-single .crane-content-inner, .crane-blog-single .crane-sidebar {
	padding-top: 80px;
	padding-bottom: 80px;
}
.crane-featured-block__page-title {
	font-family: "Open Sans";
	text-align: initial;
	line-height: 60px;
	font-weight: 600;
	font-style: normal;
	color: #ffffff;
	font-size: 46px;
}
.crane-featured-block__categories li a {
	font-family: "Open Sans";
	text-align: initial;
	line-height: 25px;
	font-weight: 600;
	font-style: normal;
	color: #ffffff;
	font-size: 16px;
}
.crane-shop-archive .crane-content-inner, .crane-shop-archive .crane-sidebar {
	padding-top: 80px;
	padding-bottom: 80px;
}
.crane-shop-single .crane-content-inner, .crane-shop-single .crane-sidebar {
	padding-top: 80px;
	padding-bottom: 80px;
}
.crane-search-page .crane-content-inner, .crane-search-page .crane-sidebar {
	padding-top: 80px;
	padding-bottom: 80px;
}
.crane-related-post__img-wrapper::before {
	background-image: linear-gradient(128deg, #7ad4f1 0%, #7ad4f1 33%, #cef17a 98%, #cef17a 100%);
}
.crane-container {
	max-width: 1200px;
}
			::-moz-selection {
background: #cccccc;
}
::selection {
	background: #cccccc;
}
.preloader {
	background-color: #ffffff;
}
.square-spin > div,  .ball-pulse > div,  .ball-pulse-sync > div,  .ball-scale > div,  .ball-rotate > div,  .ball-rotate > div::before,  .ball-rotate > div::after,  .ball-scale-multiple > div,  .ball-pulse-rise > div,  .ball-grid-pulse > div,  .ball-spin-fade-loader > div,  .ball-zig-zag > div,  .line-scale > div,  .line-spin-fade-loader > div,  .ball-clip-rotate-pulse > div:first-child,  .pacman > div:nth-child(3),  .pacman > div:nth-child(4),  .pacman > div:nth-child(5),  .pacman > div:nth-child(6) {
	background: #93cb52;
}
.ball-clip-rotate > div,  .ball-clip-rotate-multiple > div,  .ball-scale-ripple > div,  .ball-scale-ripple-multiple > div {
	border: 2px solid #93cb52;
}
.pacman > div:first-of-type,  .pacman > div:nth-child(2) {
	border-top-color: #93cb52;
	border-bottom-color: #93cb52;
	border-left-color: #93cb52;
}
.ball-clip-rotate-pulse > div:last-child,  .ball-clip-rotate-multiple > div:last-child {
	border-color: #93cb52 transparent #93cb52 transparent !important;
}
.ball-triangle-path > div {
	border: 1px solid #93cb52;
}
.crane-featured-block__page-title::after {
	background-color: rgba(251,251,251,1);
}
.cat-item a::after, .widget .menu-item a::after, .crane-archive-widget li a::after, .widget .page_item a::after {
	background-color: #686868
}
.crane-page-title {
	height: auto;
	min-height: 200px;
}
.sticky .post__main__txt-wrapper {
	background-color: rgba(147,203,82,0.2) !important;
}
@media (max-width: 768px) {
.crane-regular-page .crane-content-inner, .crane-regular-page .crane-sidebar {
	padding-top: 40px;
	padding-bottom: 40px;
}
}
@media (max-width: 768px) {
.crane-portfolio-archive .crane-content-inner, .crane-portfolio-archive .crane-sidebar {
	padding-top: 40px;
	padding-bottom: 40px;
}
}
@media (max-width: 768px) {
.crane-portfolio-single .crane-content-inner, .crane-portfolio-single .crane-sidebar {
	padding-top: 40px;
	padding-bottom: 40px;
}
}
@media (max-width: 768px) {
.crane-blog-archive .crane-content-inner, .crane-blog-archive .crane-sidebar {
	padding-top: 40px;
	padding-bottom: 40px;
}
}
@media (max-width: 768px) {
.crane-blog-single .crane-content-inner, .crane-blog-single .crane-sidebar {
	padding-top: 40px;
	padding-bottom: 40px;
}
}
@media (max-width: 768px) {
.crane-shop-archive .crane-content-inner, .crane-shop-archive .crane-sidebar {
	padding-top: 40px;
	padding-bottom: 40px;
}
}
@media (max-width: 768px) {
.crane-shop-single .crane-content-inner, .crane-shop-single .crane-sidebar {
	padding-top: 40px;
	padding-bottom: 40px;
}
}
@media (max-width: 768px) {
.crane-search-page .crane-content-inner, .crane-search-page .crane-sidebar {
	padding-top: 40px;
	padding-bottom: 40px;
}
}
</style>
<link rel='stylesheet' id='cp-module-main-style-css'  href='wp-content/plugins/convertplug/modules/assets/css/cp-module-main5010.css?ver=4.9.8' type='text/css' media='all' />
<link rel='stylesheet' id='smile-modal-style-css'  href='wp-content/plugins/convertplug/modules/modal/assets/css/modal.min5010.css?ver=4.9.8' type='text/css' media='all' />
<link rel='stylesheet' id='redux-google-fonts-crane_options-css'  href='http://fonts.googleapis.com/css?family=Open+Sans%3A300%2C400%2C600%2C700%2C800%2C300italic%2C400italic%2C600italic%2C700italic%2C800italic&amp;subset=latin&amp;ver=1539326210' type='text/css' media='all' />
<script type='text/javascript'>
/* <![CDATA[ */
var slide_in = {"demo_dir":"http:\/\/crane.grooni.com\/wp-content\/plugins\/convertplug\/modules\/slide_in\/assets\/demos"};
/* ]]> */
</script>
<script type='text/javascript' src='wp-includes/js/jquery/jqueryb8ff.js?ver=1.12.4'></script>
<script type='text/javascript' src='wp-includes/js/jquery/jquery-migrate.min330a.js?ver=1.4.1'></script>
<script type='text/javascript' src='wp-includes/js/jquery/ui/core.mine899.js?ver=1.11.4'></script>
<script type='text/javascript' src='wp-content/plugins/Ultimate_VC_Addons/assets/min-js/ultimate.min957f.js?ver=3.16.25'></script>
<link rel='https://api.w.org/' href='wp-json/index.html' />
<link rel="EditURI" type="application/rsd+xml" title="RSD" href="xmlrpc0db0.php?rsd" />
<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="wp-includes/wlwmanifest.xml" />
<meta name="generator" content="WordPress 4.9.8" />
<meta name="generator" content="WooCommerce 3.4.6" />
<link rel="canonical" href="index.html" />
<link rel='shortlink' href='index42a6.html?p=1341' />
<link rel="alternate" type="application/json+oembed" href="wp-json/oembed/1.0/embed9d55.json?url=http%3A%2F%2Fcrane.grooni.com%2Ff-a-q%2F" />
<link rel="alternate" type="text/xml+oembed" href="wp-json/oembed/1.0/embedb81b?url=http%3A%2F%2Fcrane.grooni.com%2Ff-a-q%2F&amp;format=xml" />
<noscript>
<style>
.woocommerce-product-gallery{ opacity: 1 !important; }
</style>
</noscript>
<meta name="generator" content="Powered by WPBakery Page Builder - drag and drop page builder for WordPress."/>
<!--[if lte IE 9]><link rel="stylesheet" type="text/css" href="http://crane.grooni.com/wp-content/plugins/js_composer/assets/css/vc_lte_ie9.min.css" media="screen"><![endif]-->
<link rel="icon" href="wp-content/uploads/2015/10/favicon.png" sizes="32x32" />
<link rel="icon" href="wp-content/uploads/2015/10/favicon.png" sizes="192x192" />
<link rel="apple-touch-icon-precomposed" href="wp-content/uploads/2015/10/favicon.png" />
<meta name="msapplication-TileImage" content="http://crane.grooni.com/wp-content/uploads/2015/10/favicon.png" />
<style type="text/css" id="wp-custom-css">
			.crane-buy-btn {
	display: flex;
	align-items: center;
	z-index: 100;
	text-decoration: none;
	padding: 12px 22px 12px 30px;
	box-shadow: 0 9px 24px rgba(123, 203, 90, 0.45);
	border-radius: 26px;
	background-image: linear-gradient(-93deg, #68ac10 0%, #94cb53 100%);
	position: fixed;
	bottom: 42px;
	right: 77px;
	transform: translateY(0);
	transition: 
		transform ease 0.3s,
		box-shadow ease 0.3s;
}

.crane-buy-btn:hover {
	transform: translateY(2px);
	box-shadow: none;
}

.crane-buy-btn__cart {
	margin-right: 9px;
	width: 18px;
	height: 21px;
	margin-top: -6px;
}

.crane-buy-btn__txt {
	color: #ffffff;
	font-family: Roboto;
	font-size: 14px;
	font-weight: 700;
	line-height: 25px;
	text-transform: uppercase;
	letter-spacing: 0.56px;
}

.crane-buy-btn__price {
	color: #e1ffae;
}

.crane-buy-btn__divider {
	width: 1px;
	height: 33px;
	background-color: #c3df9e;
	margin: 0 11px;
}

.crane-buy-btn__envato {
	max-width: 100%;
	height: auto;
}

@media (max-width: 410px) {
	.crane-buy-btn {
		display: none;
		bottom: 13px;
		right: 68px;
	}

	.crane-buy-btn__txt {
		font-size: 12px;
	}
}

#content .wpb_text_column :last-child,
.wpb_text_column :last-child {
	margin-bottom: auto;
}

.vc_row.vc_row-flex {
	min-width: 100%;
}

span.wpcf7-list-item {
	margin-left: 0;
}		
</style>
<noscript>
<style type="text/css"> 
.wpb_animate_when_almost_visible { opacity: 1; }
</style>
</noscript>
</head>
<body class="page-template-default page page-id-1341 groovy_menu_1-3 woocommerce-no-js crane_1-3-7-1 crane-regular-page wpb-js-composer js-comp-ver-5.5.4 vc_responsive">
<style type="text/css">
@import url(https://fonts.googleapis.com/css?family=Open+Sans:700);
</style>
<style type="text/css" id="gm-style-preset--106" class="gm-compiled-css">
.gm-container{ max-width: 1200px }.mega-gm-dropdown > .gm-dropdown-menu{ max-width: 1200px }.gm-navbar, .gm-main-menu-wrapper{ font-family: 'Open Sans', sans-serif }@media (min-width: 1023px) {.gm-inner .gm-container{ height: 100px; }}@media (min-width: 1023px) {.gm-navbar-sticky-toggle .gm-inner  .gm-container{ height: 76px; }}.gm-navbar:not(.gm-navbar-sticky-toggle) .gm-inner-bg{ background-color: rgba(255,255,255,0) }.gm-navbar:not(.gm-navbar-sticky-toggle) .gm-inner-bg{ background-repeat: no-repeat }.gm-navbar:not(.gm-navbar-sticky-toggle) .gm-inner-bg{ background-attachment: fixed }.gm-navbar:not(.gm-navbar-sticky-toggle) .gm-inner-bg{ background-position: center center }.gm-navbar-sticky-toggle .gm-inner-bg{ background-color: rgba(255,255,255,1) }.gm-navbar-sticky-toggle .gm-inner-bg{ background-repeat: no-repeat }.gm-navbar-sticky-toggle .gm-inner-bg{ background-attachment: scroll }.gm-navbar-sticky-toggle .gm-inner-bg{ background-position: center center }.gm-navbar-sticky-toggle .gm-inner{ border-bottom-color: rgba(0,0,0,0); border-bottom-width: 0px }@media (min-width: 1023px) {.gm-navbar-nav .gm-dropdown-menu .gm-menu-item__link, .gm-mega-menu__item__title{ border-bottom: 1px dotted rgba(110, 110, 111, 1); }}@media (min-width: 1023px) {.gm-navbar:not(.gm-navbar--style-3) .gm-toolbar{ border-top: 0px solid rgba(0,0,0,1); }}@media (max-width: 1023px) {.gm-toolbar{ border-top: 0px solid rgba(0,0,0,1); }}@media (min-width: 1023px) {.gm-navbar:not(.gm-navbar--style-3) .gm-toolbar{ border-bottom: 1px solid #cccccc; }}@media (max-width: 1023px) {.gm-toolbar{ border-bottom: 1px solid #cccccc; }}.gm-navbar:not(.gm-navbar-sticky-toggle) .gm-inner{ border-bottom-color: rgba(255,255,255,0.3) }.gm-navbar:not(.gm-navbar-sticky-toggle) .gm-inner{ border-bottom-width: 0px }.gm-navbar-nav .gm-menu-item__icon{ display:none }@media (min-width: 1023px) {.gm-navbar--style-4 .gm-navbar-nav > .gm-menu-item > a, .gm-navbar--style-4 .gm-logo, .gm-navbar--style-4 .gm-search, .gm-navbar--style-4 .gm-minicart, .gm-navbar--style-4 .gm-toolbar-social-link{ border-bottom-width: 1px }}@media (min-width: 1023px) {.gm-navbar--style-4 .gm-navbar-nav > .gm-menu-item > a, .gm-navbar--style-4 .gm-logo, .gm-navbar--style-4 .gm-search, .gm-navbar--style-4 .gm-minicart, .gm-navbar--style-4 .gm-toolbar-social-link{ border-bottom-color: rgba(0,0,0,0) }}@media (min-width: 1023px) {.gm-navbar--style-4 .gm-navbar-nav > .gm-menu-item > a, .gm-navbar--style-4 .gm-logo, .gm-navbar--style-4 .gm-search, .gm-navbar--style-4 .gm-minicart, .gm-navbar--style-4 .gm-toolbar-social-link{ border-bottom-style: solid }}@media (min-width: 1023px) {.gm-navbar--style-4 .gm-menu-item__link{ border-bottom-width: 1px }}@media (min-width: 1023px) {.gm-navbar--style-4 .gm-menu-item__link{ border-bottom-color: rgba(0,0,0,0) }}@media (min-width: 1023px) {.gm-navbar--style-4 .gm-menu-item__link{ border-bottom-style: solid }}@media (min-width: 1023px) {.gm-navbar--style-4 .gm-navbar-nav > .gm-menu-item > a, .gm-navbar--style-4 .gm-logo{ border-bottom-style: solid }}@media (min-width: 1023px) {.gm-dropdown-menu--lvl-1{ background-color: rgba(0,0,0,1) }}@media (min-width: 1023px) {.gm-navbar--style-2 ~ .gm-main-menu-wrapper{ background-color: rgba(0,0,0,1) }}@media (min-width: 1023px) {.gm-navbar--style-2 ~ .gm-main-menu-wrapper .gm-dropdown-menu--lvl-1{ background-color: rgba(0,0,0,1) }}@media (min-width: 1023px) {.gm-navbar--style-2 ~ .gm-main-menu-wrapper .gm-dropdown-menu:not(.gm-dropdown-menu--lvl-1){ background-color: rgba(0,0,0,1) }}@media (min-width: 1023px) {.gm-navbar-nav > .menu-item > a, .gm-search > i, .gm-minicart-icon-wrapper > i, .gm-minicart-icon-wrapper > .gm-minicart__txt, .gm-search > .gm-search__txt{ color: #ffffff }}@media (min-width: 1023px) {.gm-navbar--style-3 .gm-actions > div:nth-of-type(n+2){ border-color: #ffffff }}@media (min-width: 1023px) {.gm-navbar:not(.gm-navbar-sticky-toggle) .gm-nav-inline-divider, .gm-navbar:not(.gm-navbar-sticky-toggle).gm-navbar--has-divider .gm-navbar-nav > li:not(:last-of-type) > a::before{ background-color: #ffffff }}@media (min-width: 1023px) {.gm-navbar-sticky-toggle .gm-nav-inline-divider, .gm-navbar-sticky-toggle.gm-navbar--has-divider .gm-navbar-nav > li:not(:last-of-type) > a::before{ background-color: #5a5a5a }}@media (min-width: 1023px) {.gm-search > i{ font-size: 17px }}@media (max-width: 1023px) {.gm-search > i{ font-size: 17px }}@media (min-width: 1023px) {.gm-minicart-icon-wrapper > i{ font-size: 16px }}@media (max-width: 1023px) {.gm-minicart-icon-wrapper > i{ font-size: 17px }}@media (min-width: 1023px) {.gm-navbar .wpml-ls-flag{ height: auto; width: 18px }}@media (max-width: 1023px) {.gm-navbar .wpml-ls-flag{ height: auto; width: 18px }}@media (min-width: 1023px) {.gm-navbar-sticky-toggle .gm-navbar-nav > li > a, .gm-navbar-sticky-toggle .gm-search > i, .gm-navbar-sticky-toggle .gm-minicart-icon-wrapper > i{ color: #5a5a5a }}@media (min-width: 1023px) {.gm-navbar-sticky-toggle .gm-nav-inline-divider{ background-color: #5a5a5a }}@media (min-width: 1023px) {.gm-navbar-nav > .current-menu-item > a, .gm-navbar-nav > .current-menu-ancestor > a, .gm-navbar-nav > .menu-item > a:hover, .gm-navbar-nav > .menu-item.is-open > a{ background-color: #93cb52 }}@media (min-width: 1023px) {.gm-navbar-nav > li > a:hover, .gm-navbar-nav > .menu-item.is-open > a, .gm-navbar-nav li.current-menu-ancestor.is-open > a, .gm-navbar-nav li.current-menu-item > a.gm-menu-item__link, .gm-navbar-nav li.current-menu-ancestor > a, .gm-navbar-nav li.current-menu-item > a, .gm-navbar-nav li.current-menu-parent:not(.current-post-ancestor) > a{ color: #ffffff }}@media (min-width: 1023px) {.gm-navbar-sticky-toggle .navbar-nav > li.current-menu-parent > a, .gm-navbar-sticky-toggle .gm-navbar-nav > li.current-menu-ancestor > a, .gm-navbar-sticky-toggle .gm-navbar-nav > li.current-menu-item > a, .gm-navbar-sticky-toggle .gm-navbar-nav > li > a:hover, .gm-navbar-sticky-toggle .gm-navbar-nav > .menu-item.is-open > a{ background-color: #93cb52 }}@media (min-width: 1023px) {.gm-navbar-sticky-toggle .gm-navbar-nav > li > a:hover, .gm-navbar-sticky-toggle .gm-navbar-nav > .menu-item.is-open > a, .gm-navbar-sticky-toggle .gm-navbar-nav li.current-menu-ancestor.is-open > a, .gm-navbar-sticky-toggle .gm-navbar-nav li.current-menu-ancestor > a, .gm-navbar-sticky-toggle .gm-navbar-nav li.current-menu-item > a, .gm-navbar-sticky-toggle .gm-navbar-nav li.current-menu-parent:not(.current-post-ancestor) > a{ color: #ffffff }}@media (min-width: 1023px) {.gm-navbar-nav > .gm-dropdown:not(.mega-gm-dropdown) .gm-dropdown-menu{ min-width: 230px }}@media (min-width: 1023px) {.gm-navbar-nav .gm-dropdown-menu{ border-top: 3px solid #93cb52 }}@media (min-width: 1023px) {.gm-navbar-nav .gm-dropdown-menu, .gm-minicart-dropdown{ background-color: #202022 }}@media (min-width: 1023px) {.gm-navbar-nav .gm-dropdown-menu .gm-menu-item__link{ color: #6e6e6f }}@media (min-width: 1023px) {.gm-navbar-nav .gm-dropdown-menu .gm-menu-item__link:hover{ color: #93cb52 }}@media (min-width: 1023px) {.gm-navbar-nav .gm-dropdown-menu .current-menu-ancestor > .gm-menu-item__link, .gm-navbar-nav .gm-dropdown-menu .current-menu-item .gm-menu-item__link { color: #93cb52 }}@media (min-width: 1023px) {.gm-mega-menu__item__title{ color:#ffffff }}@media (max-width: 1023px) {.gm-main-menu-wrapper{ width:250px }}@media (max-width: 1023px) {.gm-navbar-offcanvas--left{ transform: translate3d(250px,0,0) !important }}@media (max-width: 1023px) {.gm-navbar-offcanvas--left{ -webkit-transform: translate3d(250px,0,0) !important }}@media (max-width: 1023px) {.gm-navbar-offcanvas--right{ transform: translate3d(-250px,0,0) !important }}@media (max-width: 1023px) {.gm-navbar-offcanvas--right{ -webkit-transform: translate3d(-250px,0,0) !important }}@media (max-width: 1023px) {.gm-inner .gm-container{ height: 70px }}@media (max-width: 1023px) {.gm-navbar-sticky-toggle .gm-inner .gm-container{ height: 70px }}@media (min-width: 1023px) {.gm-navbar-nav > .gm-menu-item > a{ margin-left: 2px }}@media (min-width: 1023px) {.gm-navbar-nav > .gm-menu-item > a{ margin-right: 2px }}@media (min-width: 1023px) {.gm-navbar--has-divider .gm-navbar-nav > li:not(:last-of-type) > a::before{ right: -2px }}@media (min-width: 1023px) {.gm-navbar-nav > li > a{ font-size: 13px }}@media (min-width: 1023px) {.gm-menu-item__link{ font-size: 11px }}@media (min-width: 1023px) {.gm-navbar-nav > li > a{ text-transform: uppercase }}@media (min-width: 1023px) {.gm-menu-item__link{ text-transform: uppercase }}@media (min-width: 1023px) {.gm-mega-menu__item__title{ text-transform: uppercase }}@media (min-width: 1023px) {.gm-mega-menu__item__title{ font-size: 13px }}@media (min-width: 1023px) {.gm-mega-menu__item__title{ font-weight: 700 }}@media (min-width: 1023px) {.gm-navbar-nav > li > a{ font-weight: 700 }}@media (min-width: 1023px) {.gm-menu-item__link{ font-weight: 700 }}@media (min-width: 1023px) {.gm-navbar-nav > li > a{ letter-spacing: 0px }}@media (min-width: 1023px) {.gm-menu-item__link{ letter-spacing: 0px }}@media (min-width: 1023px) {.gm-menu-item__link{ letter-spacing: 0px }}.gm-toolbar-bg{ background-color: rgba(255,255,255,1) }.gm-toolbar-contacts, #lang_sel_click ul ul a:visited, #lang_sel_click ul ul a, #lang_sel_click a:hover, #lang_sel_click ul ul a:hover, #lang_sel_click:hover> a, #lang_sel_click ul ul:hover> a, #lang_sel_click a.lang_sel_sel, #lang_sel_click a.lang_sel_sel:hover{ color: rgba(104,104,104,1) }.gm-toolbar-contacts{ font-size: 14px; }#lang_sel_click ul ul a:visited, #lang_sel_click ul ul a, #lang_sel_click ul ul a:hover{ background-color: rgba(255,255,255,1) }#lang_sel_click{ display: none }.gm-toolbar-social-link{ color: rgba(104,104,104,1) }.gm-toolbar-socials-list__item{ border-right: 1px solid rgba(104,104,104,1) }.gm-toolbar-socials-list__item:first-of-type{ border-left: 1px solid rgba(104,104,104,1) }.gm-navbar--style-3 .gm-toolbar-socials-list__item{ box-shadow: 1px 0 0 0 rgba(104,104,104,1), 0 1px 0 0 rgba(104,104,104,1), 1px 1px 0 0 rgba(104,104,104,1), 1px 0 0 0 rgba(104,104,104,1) inset, 0 1px 0 0 rgba(104,104,104,1) inset }@media (min-width: 1023px) {.gm-menu-btn__inner{ color: #686868; }}@media (min-width: 1023px) {.gm-menu-btn__inner{ font-size: 24px; }}@media (min-width: 1023px) {.gm-menu-btn__inner{ padding: 0px; }}@media (min-width: 1023px) {.gm-menu-btn__inner{ background-color: rgba(0,0,0,0); }}@media (min-width: 1023px) {.gm-navbar-sticky-toggle .gm-menu-btn__inner{ color: rgba(104,104,104,1); }}@media (min-width: 1023px) {.gm-navbar-sticky-toggle .gm-menu-btn__inner{ font-size: 24px; }}@media (min-width: 1023px) {.gm-navbar-sticky-toggle .gm-menu-btn__inner{ background-color: rgba(0,0,0,0); }}@media (min-width: 1023px) {.gm-navbar-sticky-toggle .gm-menu-btn__inner{ padding: 0px; }}@media (max-width: 1023px) {.gm-menu-btn__inner{ color: #ffffff; }}@media (max-width: 1023px) {.gm-menu-btn__inner{ font-size: 24px; }}@media (max-width: 1023px) {.gm-menu-btn__inner{ background-color: rgba(0,0,0,0); }}@media (max-width: 1023px) {.gm-menu-btn__inner{ padding: 0px; }}@media (max-width: 1023px) {.gm-navbar-sticky-toggle .gm-menu-btn__inner{ color: rgba(104,104,104,1); }}@media (max-width: 1023px) {.gm-navbar-sticky-toggle .gm-menu-btn__inner{ font-size: 24px; }}@media (max-width: 1023px) {.gm-navbar-sticky-toggle .gm-menu-btn__inner{ background-color: rgba(0,0,0,0); }}@media (max-width: 1023px) {.gm-navbar-sticky-toggle .gm-menu-btn__inner{ padding: 0px; }}@media (max-width: 1023px) {.gm-navbar-sticky-toggle .gm-menu-btn__inner{ border: 0px solid rgba(0,0,0,0); }}@media (min-width: 1023px) {.mini_cart_item a:not(.remove){ color: #ffffff; }}@media (min-width: 1023px) {.gm-minicart-dropdown .checkout{ color: #686868; }}@media (min-width: 1023px) {.gm-minicart-dropdown .checkout:hover{ color: #686868; }}@media (min-width: 1023px) {.gm-minicart-dropdown .checkout{ font-size: 13px; }}@media (min-width: 1023px) {.gm-minicart-dropdown .checkout{ font-weight: 700; }}@media (min-width: 1023px) {.gm-minicart-dropdown .checkout{ background-color: #ffffff; }}@media (min-width: 1023px) {.gm-minicart-dropdown .checkout:hover{ background-color: #ffffff; }}@media (min-width: 1023px) {.gm-minicart-dropdown .checkout{ border-style: none; }}@media (min-width: 1023px) {.gm-minicart-dropdown a.button:first-of-type{ color: #ffffff; }}@media (min-width: 1023px) {.gm-minicart-dropdown a.button:first-of-type:hover{ color: #ffffff; }}@media (min-width: 1023px) {.gm-minicart-dropdown a.button:first-of-type{ font-size: 13px; }}@media (min-width: 1023px) {.gm-minicart-dropdown a.button:first-of-type{ font-weight: 700; }}@media (min-width: 1023px) {.gm-minicart-dropdown a.button:first-of-type{ background-color: #a5e25e; }}@media (min-width: 1023px) {.gm-minicart-dropdown a.button:first-of-type:hover{ background-color: #a5e25e; }}@media (min-width: 1023px) {.gm-minicart-dropdown a.button:first-of-type{ border-style: none; }}@media (min-width: 1023px) {.gm-mega-menu__item:after{ border-right: 1px solid rgba(255,255,255,0); }}@media (min-width: 1023px) {.gm-toolbar-social-link:hover{ color: #a5e25e }}.gm-toolbar-socials-list__item{ border: none!important }.gm-toolbar-social-link i{ font-size: 16px }@media (min-width: 1023px) {.gm-logo > a > img{ height: 46px }}@media (min-width: 1023px) {.gm-navbar-sticky-toggle .gm-logo > a > img{ height: 46px }}@media (max-width: 1023px) {.gm-logo > a > img{ height: 44px }}@media (max-width: 1023px) {.gm-navbar-sticky-toggle .gm-logo > a > img{ height: 44px }}@media (min-width: 1023px) {.gm-navbar:not(.gm-navbar-sticky-toggle) .gm-logo__img-default{ display: none; }}@media (min-width: 1023px) {.gm-navbar:not(.gm-navbar-sticky-toggle) .gm-logo__img-alt{ display: flex; }}@media (min-width: 1023px) {.gm-navbar-sticky-toggle .gm-logo__img-sticky{ display: flex; }}@media (min-width: 1023px) {.gm-navbar-sticky-toggle .gm-logo__img-sticky-alt{ display: none; }}@media (max-width: 1023px) {.gm-navbar:not(.gm-navbar-sticky-toggle) .gm-logo__img-mobile{ display: flex; }}@media (max-width: 1023px) {.gm-navbar:not(.gm-navbar-sticky-toggle) .gm-logo__img-mobile-alt{ display: none; }}@media (max-width: 1023px) {.gm-navbar-sticky-toggle .gm-logo__img-sticky-mobile{ display: flex; }}@media (max-width: 1023px) {.gm-navbar-sticky-toggle .gm-logo__img-sticky-alt-mobile{ display: none; }}@media (min-width: 1023px) {.gm-search:not(.fullscreen) .gm-search-wrapper{ position: absolute; top: 100%; right: 0; width: 350px; padding: 15px 20px; transition: opacity ease 0.3s, visibility ease 0.3s; border-right: 4px solid #93cb52; border-top-left-radius: 4px; border-bottom-left-radius: 4px; background-color: #fff; box-shadow: 0 0 5px rgba(0, 1, 0, 0.3); }.gm-search > i{ padding-left: 15px; padding-right: 13px; cursor: pointer; }.gm-minicart > a{ padding-left: 15px; }.gm-grid-container{ margin-right: auto; margin-left: auto; padding: 20px 15px; }.gm-grid-row{ display: flex; flex-direction: row; margin-right: -15px; margin-left: -15px; flex: 0 1 auto; flex-wrap: wrap; }.grid-5, .grid-10, .grid-15, .grid-20, .grid-25, .grid-30, .grid-35, .grid-40, .grid-45, .grid-50, .grid-55, .grid-60, .grid-65, .grid-70, .grid-75, .grid-80, .grid-85, .grid-90, .grid-95, .grid-100, .grid-33, .grid-66{ position: relative; box-sizing: border-box; padding-right: 15px; padding-left: 15px; flex: 0 0 auto; }.hide-on-desktop{ display: none !important; }.grid-5{ max-width: 5%; flex-basis: 5%; }.grid-10{ max-width: 10%; flex-basis: 10%; }.grid-15{ max-width: 15%; flex-basis: 15%; }.grid-20{ max-width: 20%; flex-basis: 20%; }.grid-25{ max-width: 25%; flex-basis: 25%; }.grid-30{ max-width: 30%; flex-basis: 30%; }.grid-35{ max-width: 35%; flex-basis: 35%; }.grid-40{ max-width: 40%; flex-basis: 40%; }.grid-45{ max-width: 45%; flex-basis: 45%; }.grid-50{ max-width: 50%; flex-basis: 50%; }.grid-55{ max-width: 55%; flex-basis: 55%; }.grid-60{ max-width: 60%; flex-basis: 60%; }.grid-65{ max-width: 65%; flex-basis: 65%; }.grid-70{ max-width: 70%; flex-basis: 70%; }.grid-75{ max-width: 75%; flex-basis: 75%; }.grid-80{ max-width: 80%; flex-basis: 80%; }.grid-85{ max-width: 85%; flex-basis: 85%; }.grid-90{ max-width: 90%; flex-basis: 90%; }.grid-95{ max-width: 95%; flex-basis: 95%; }.grid-33{ max-width: 33.33333%; flex-basis: 33.33333%; }.grid-66{ max-width: 66.66667%; flex-basis: 66.66667%; }.grid-100{ max-width: 100%; flex-basis: 100%; }.gm-navbar--style-1 .gm-container{ padding-right: 15px; padding-left: 15px; flex: 1 100%; }.gm-navbar--style-1 .gm-minicart-icon-wrapper i{ display: block; }.gm-navbar--style-1 .gm-menu-item:last-of-type:not(:only-of-type) > .gm-menu-item__link{ border-bottom: none; }.gm-navbar--style-1 .gm-dropdown-menu-wrapper--left{ right: 0; left: auto; }.gm-navbar--style-1 .gm-dropdown-submenu .gm-dropdown-menu-wrapper{ left: 100%; }.gm-navbar--style-1 .gm-dropdown-submenu .gm-dropdown-menu-wrapper--left{ right: 100%; left: auto; }.gm-navbar--style-1 #gm-main-menu{ flex-grow: 1; display: flex; }.gm-navbar--style-1 .gm-main-menu-wrapper{ flex-grow: 1; align-items: stretch; }.gm-navbar--style-1 .gm-minicart{ margin-right: 17px; }.gm-navbar--style-1 .gm-minicart > a{ height: 30px; padding-right: 15px }.gm-navbar--style-1.gm-top-links-align-left #gm-main-menu{ justify-content: flex-start; }.gm-navbar--style-1.gm-top-links-align-center #gm-main-menu{ justify-content: center; }.gm-navbar--style-1.gm-top-links-align-center .gm-logo{ position: absolute; top: 50%; transform: translateY(-50%); }.gm-navbar--style-1.gm-top-links-align-right #gm-main-menu{ justify-content: flex-end; }.gm-navbar--style-2 .gm-container{ padding-right: 15px; padding-left: 15px; }.gm-navbar--style-2 ~ .gm-main-menu-wrapper{ position: fixed; z-index: 9999; width: 300px; justify-content: center; }.gm-navbar--style-2 .gm-toolbar{ box-sizing: content-box; }.gm-navbar--style-2 ~ .gm-main-menu-wrapper #gm-main-menu{ flex: 1 100%; }.gm-navbar--style-2 ~ .gm-main-menu-wrapper .gm-navbar-nav{ flex-direction: column; }.gm-navbar--style-2 ~ .gm-main-menu-wrapper .gm-navbar-nav .gm-menu-item{ position: static; display: flex; }.gm-navbar--style-2 ~ .gm-main-menu-wrapper .gm-navbar-nav > .gm-menu-item{ padding-right: 53px; padding-left: 53px; }.gm-navbar--style-2 ~ .gm-main-menu-wrapper .gm-navbar-nav > li > a{ padding: 7px 0; }.gm-navbar--style-2 ~ .gm-main-menu-wrapper .gm-menu-item__link{ position: relative; }.gm-navbar--style-2 ~ .gm-main-menu-wrapper .gm-dropdown-menu .gm-menu-item{ padding-right: 0; padding-left: 0; }.gm-navbar--style-2 ~ .gm-main-menu-wrapper .gm-dropdown-menu .gm-menu-item__link{ padding-right: 32px; padding-left: 32px; }.gm-navbar--style-2 ~ .gm-main-menu-wrapper .gm-dropdown-menu .groovy-menu-wim-wrap{ padding-right: 32px; padding-left: 32px; }.gm-navbar--style-2 ~ .gm-main-menu-wrapper .gm-dropdown-menu .gm-menu-item__link::after{ position: absolute; right: 32px; bottom: 0; left: 32px; content: ""; }.gm-navbar--style-2 ~ .gm-main-menu-wrapper .gm-actions{ position: fixed; bottom: 100px; z-index: 999; justify-content: center; }.gm-navbar--style-2 ~ .gm-main-menu-wrapper .gm-actions > div:nth-of-type(n+2){ border-left-width: 1px; border-left-style: solid; }.gm-navbar--style-2 ~ .gm-main-menu-wrapper .gm-minicart{ margin: 0; text-align: center; }.gm-navbar--style-2.gm-navbar--align-right ~ .gm-main-menu-wrapper #cart-counter{ top: -24px; right: -15px; left: auto; border-radius: 50% 50% 50% 0; }.gm-navbar--style-2 ~ .gm-main-menu-wrapper .gm-minicart > a, .gm-navbar--style-2 ~ .gm-main-menu-wrapper .gm-search > i{ padding: 0; line-height: 1; }.gm-navbar--style-2 ~ .gm-main-menu-wrapper .gm-minicart-icon-wrapper i, .gm-navbar--style-2 ~ .gm-main-menu-wrapper .gm-search > i{ display: block; padding-bottom: 15px; line-height: 1; }.gm-navbar--style-2 ~ .gm-main-menu-wrapper .gm-search{ text-align: center; }.gm-navbar--style-2 ~ .gm-main-menu-wrapper .gm-minicart__txt, .gm-navbar--style-2 ~ .gm-main-menu-wrapper .gm-search__txt{ display: block; text-transform: uppercase; font-weight: 700; line-height: 1; }.gm-navbar--style-2 ~ .gm-main-menu-wrapper .gm-dropdown-menu{ top: 0; bottom: 0; display: flex; flex-direction: column; width: 100%; height: 100%; justify-content: center; }.gm-navbar--style-2 ~ .gm-main-menu-wrapper .gm-dropdown-menu-wrapper{ width: 100%; height: 100%; }.gm-navbar--style-3{ position: fixed; z-index: 1041; box-sizing: content-box; width: 300px; height: 100%; }.gm-navbar--style-3 .gm-wrapper{ position: relative; height: 100vh; }.gm-navbar--style-3 .gm-inner{ height: 100%; }.gm-navbar--style-3 .gm-container{ height: 100%; }.gm-navbar--style-3 .gm-toolbar{ position: absolute; z-index: 1005; bottom: 20px; width: 100%; text-align: center; }.admin-bar .gm-navbar--style-3 .gm-toolbar{ bottom: 52px; }.gm-navbar--style-3 .gm-toolbar-right{ flex-direction: column; }.gm-navbar--style-3 .gm-toolbar-socials-list{ order: 2; }.gm-navbar--style-3 #lang_sel_click{ align-self: center; }.gm-navbar--style-3 #lang_sel_click li{ width: auto; }.gm-navbar--style-3 #lang_sel_click a{ padding-left: 0 !important; }.gm-navbar--style-3 .gm-toolbar .gm-container{ flex-direction: column; }.gm-navbar--style-3 .gm-toolbar-social-link{ width: 42px; height: 42px; }.gm-navbar--style-3 .gm-toolbar-socials-list__item{ padding-left: 0; padding-right: 0; }.gm-navbar--style-3 .gm-toolbar-email, .gm-navbar--style-3 .gm-toolbar-phone{ display: none; }.gm-navbar--style-3 .gm-logo{ position: absolute; width: 100%; margin-top: 40px; }.gm-navbar--style-3 .gm-logo__img{ max-width: 100% !important; margin-right: auto; margin-left: auto; }.gm-navbar--style-3 .gm-actions{ position: fixed; bottom: 100px; z-index: 999; justify-content: center; }.gm-navbar--style-3 .gm-actions > div:nth-of-type(n+2){ border-left-width: 1px; border-left-style: solid; }.gm-navbar--style-3 .gm-minicart__txt, .gm-navbar--style-3 .gm-search__txt{ display: block; text-transform: uppercase; font-weight: 700; line-height: 1; }.gm-navbar--style-3 .gm-minicart{ margin: 0; text-align: center; }.gm-navbar--style-3 .gm-search{ text-align: center; }.gm-navbar--style-3 .gm-minicart > a, .gm-navbar--style-3 .gm-search > i{ padding: 0; line-height: 1; }.gm-navbar--style-3 .gm-minicart-icon-wrapper i, .gm-navbar--style-3 .gm-search > i{ display: block; padding-bottom: 15px; line-height: 1; }.gm-navbar--style-3 #cart-counter{ top: -24px; right: -15px; }.gm-navbar--style-3 .gm-main-menu-wrapper{ flex: 1 100%; justify-content: center; }.gm-navbar--style-3 #gm-main-menu{ flex: 1 100%; }.gm-navbar--style-3 .gm-navbar-nav{ display: flex; flex-direction: column; width: 100%; height: 100%; justify-content: center; }.gm-navbar--style-3 .gm-navbar-nav > .gm-menu-item{ padding-right: 56px; padding-left: 56px; }.gm-navbar--style-3 .gm-dropdown-menu-wrapper{ width: 100%; height: 100%; }.gm-navbar--style-3 .gm-dropdown-menu .gm-menu-item{ padding-right: 0; padding-left: 0; }.gm-navbar--style-3 .gm-dropdown-menu .gm-menu-item__link{ padding-right: 32px; padding-left: 32px; }.gm-navbar--style-3 .gm-dropdown-menu .groovy-menu-wim-wrap{ padding-right: 32px; padding-left: 32px; }.gm-navbar--style-3 .gm-dropdown-menu .gm-menu-item__link::after{ position: absolute; right: 32px; bottom: 0; left: 32px; content: ""; }.gm-navbar--style-3 .gm-menu-item{ position: static; transition: background-color ease 0.2s; }.gm-navbar--style-3 .gm-mega-menu-wrapper{ position: relative; }.gm-navbar--style-3 .gm-mega-menu__item__title{ display: block; clear: both; padding: 12px 20px; cursor: pointer; white-space: nowrap; text-transform: uppercase; color: #5a5a5a; border-bottom: none; font-size: 11px; font-weight: 700; line-height: 25px; }.gm-navbar--style-3 .gm-dropdown-menu{ top: 0; right: 0; left: 100%; display: flex; flex-direction: column; height: 100%; justify-content: center; }.gm-navbar--style-3 .gm-minicart-dropdown{ top: 100%; }.gm-navbar--style-3 .gm-menu-item__link{ position: relative; padding-right: 0; padding-left: 0; }.gm-navbar--style-4 .gm-container{ flex-direction: column; }.gm-navbar--style-4{ position: fixed; z-index: 999; box-sizing: content-box; width: 70px; height: 100%; }.gm-navbar--style-4 .gm-toolbar-contacts, .gm-navbar--style-4 .gm-toolbar-email, .gm-navbar--style-4 .gm-toolbar-phone{ display: none; }.gm-navbar--style-4 #gm-main-menu{ width: 100%; }.gm-navbar--style-4 .gm-wrapper{ position: relative; display: flex; flex-direction: column; transform: none; backface-visibility: visible; perspective: none; }.gm-navbar--style-4 .gm-toolbar-left, .gm-navbar--style-4 .gm-toolbar-right{ flex-direction: column; }.gm-navbar--style-4 #lang_sel_click li{ width: 70px !important; }.gm-navbar--style-4 #lang_sel ul li a, .gm-navbar--style-4 #lang_sel_click ul li a{ padding: 0 5px !important; }.gm-navbar--style-4 .gm-toolbar-socials-list{ flex-direction: column; margin-left: 0 !important; margin-right: 0 !important; width: 100%; }.gm-navbar--style-4 .gm-main-menu-wrapper{ flex-direction: column; }.gm-navbar--style-4 .gm-toolbar{ order: 1; }.gm-navbar--style-4 .gm-toolbar-social-link{ width: auto; height: 70px; text-align: center; line-height: 70px; }.gm-navbar--style-4 .gm-toolbar-social-link i{ position: static; transform: none; line-height: 70px; }.gm-navbar--style-4 .gm-logo__img-header-4{ display: block; }.gm-navbar--style-4 .gm-navbar-nav{ flex-direction: column; }.gm-navbar--style-4 .gm-navbar-nav .gm-dropdown-menu li:only-child > a{ border-bottom: none; }.gm-navbar--style-4 .gm-navbar-nav > .gm-menu-item{ position: relative; width: 100%; transition: background-color ease 0.2s; }.gm-navbar--style-4 .gm-navbar-nav > .gm-menu-item > a{ display: block; height: 70px; padding: 0; line-height: 70px; }.gm-navbar--style-4 .gm-navbar-nav > .gm-menu-item > a > .gm-menu-item__txt{ position: absolute; top: 0; visibility: hidden; padding-right: 15px; padding-left: 15px; transition: opacity 0.3s, visibility 0.3s; opacity: 0; }.gm-navbar--style-4 .gm-navbar-nav > .gm-menu-item.is-open > a > .gm-menu-item__txt{ visibility: visible; opacity: 1; }.gm-navbar--style-4 .gm-menu-item__icon{ display: block; text-align: center; line-height: 70px; }.gm-navbar--style-4 .gm-mega-menu-wrapper{ position: relative; }.gm-navbar--style-4 .gm-actions{ flex-direction: column; }.gm-navbar--style-4 .gm-search{ height: 70px; text-align: center; line-height: 70px; box-sizing: content-box; width: 70px; }.gm-navbar--style-4 .gm-minicart{ display: flex; height: 70px; margin: 0; text-align: center; line-height: 70px; }.gm-navbar--style-4 .gm-minicart > a{ float: none; box-sizing: content-box; width: 70px; padding: 0; }.gm-navbar--style-4 #cart-counter{ top: 5px; right: -26px; }.gm-navbar--style-4 .navbar.gm-navbar--align-right #cart-counter{ top: -2px; right: -25px; left: auto; border-radius: 50% 50% 50% 0; }.gm-navbar--style-4 .gm-mega-menu__item__title{ display: block; clear: both; padding: 12px 20px; cursor: pointer; white-space: nowrap; text-transform: uppercase; color: #5a5a5a; border-bottom: none; font-size: 11px; font-weight: 700; line-height: 25px; }.gm-navbar--style-4 .gm-dropdown-menu{ top: 100%; }.gm-navbar--style-4.gm-navbar--align-left .gm-dropdown-menu{ right: auto; }.gm-navbar--style-4.gm-navbar--align-right .gm-dropdown-menu{ left: auto; }.gm-navbar--style-4 .gm-dropdown-menu--lvl-2, .gm-navbar--style-4 .gm-dropdown-menu--lvl-3{ top: -3px; }.gm-navbar--style-4 .gm-minicart-dropdown{ top: 0; }.gm-navbar--style-1 .gm-toolbar-bg, .gm-navbar--style-2 .gm-toolbar-bg{ position: absolute; top: 0; left: 0; width: 100%; height: 100%; transition: opacity 0.2s; z-index: -1; }.gm-dropdown-menu--background{ background-size: cover; }.gm-navbar--align-right .gm-search-wrapper, .gm-navbar--align-right .gm-minicart-dropdown{ right: auto; left: -15px; }.gm-nav-inline-divider{ margin: 0 10px; width: 1px; height: 30px; align-self: center; }.gm-navbar .attachment-menu-thumb, .gm-main-menu-wrapper .attachment-menu-thumb{ position: absolute; z-index: 1; top: 0; display: none; max-width: none; opacity: 0; transition: opacity 0.2s 0.5s; }.gm-navbar:not(.gm-navbar--align-right) .attachment-menu-thumb{ left: calc(100% - 30px); }.gm-navbar.gm-navbar--align-right .attachment-menu-thumb{ right: 100%; }.gm-menu-item.has-attachment-thumbnail:hover .attachment-menu-thumb{ display: block; }.gm-navbar.gm-navbar--style-2 ~ .gm-main-menu-wrapper .attachment-menu-thumb, .gm-navbar.gm-navbar--style-3 .attachment-menu-thumb{ display: none; }.gm-dropdown-appearance-animate-from-bottom .is-closed > .gm-search-wrapper{ display: none; visibility: hidden; opacity: 0; }.gm-dropdown-appearance-animate-from-bottom .gm-dropdown-menu{ transition: all 0.2s; transform: translateY(40px); }.gm-dropdown-appearance-animate-from-bottom .gm-dropdown-menu, .gm-dropdown-appearance-animate-from-bottom .gm-minicart-dropdown{ visibility: hidden; transform: translateY(40px); opacity: 0; }.gm-dropdown-appearance-animate-from-bottom .is-open > .gm-dropdown-menu-wrapper > .gm-dropdown-menu, .gm-dropdown-appearance-animate-from-bottom .is-open > .gm-minicart-dropdown, .gm-dropdown-appearance-animate-from-bottom .is-open > .gm-search-wrapper{ visibility: visible; transform: translateY(0); opacity: 1; }.gm-dropdown-menu{ position: absolute; }.gm-dropdown-menu-wrapper{ position: absolute; left: 0; visibility: hidden; }.gm-dropdown-submenu{ overflow: hidden; }.gm-menu-item__link:hover, .gm-menu-item__link:focus, .gm-dropdown-menu > .current-menu-ancestor > .gm-menu-item__link, .gm-dropdown-menu > .current-menu-ancestor > .gm-menu-item__link:hover, .gm-dropdown-menu > .current-menu-ancestor > .gm-menu-item__link:focus{ outline: 0; }.gm-navbar:not(.gm-navbar--style-2) .gm-menu-btn, .gm-minicart__txt, .gm-search__txt{ display: none; }.gm-navbar-sticky-toggle .gm-logo__img-default, .gm-navbar-sticky-toggle .gm-logo__img-alt{ display: none; }.gm-navbar--style-3.gm-navbar-sticky-toggle .gm-wrapper, .gm-navbar--style-4.gm-navbar-sticky-toggle .gm-wrapper{ transform: none !important; }.gm-navbar--style-1 .gm-navbar-nav > .gm-menu-item > a > .gm-caret{ transform: none; }[dir='rtl'] .gm-caret{ transform: rotate(180deg); }}@media (max-width: 1023px) {.gm-search.gm-dropdown .gm-search-wrapper{ display: none; }.gm-search > .gm-search-wrapper{ display: none; }.gm-search > .gm-search__txt{ margin-top: 8px; }.gm-grid-container{ margin-right: auto; margin-left: auto; padding-right: 15px; padding-left: 15px; }.gm-grid-row{ display: flex; flex-direction: row; margin-right: -15px; margin-left: -15px; flex: 0 1 auto; flex-wrap: wrap; }.mobile-grid-5, .mobile-grid-10, .mobile-grid-15, .mobile-grid-20, .mobile-grid-25, .mobile-grid-30, .mobile-grid-35, .mobile-grid-40, .mobile-grid-45, .mobile-grid-50, .mobile-grid-55, .mobile-grid-60, .mobile-grid-65, .mobile-grid-70, .mobile-grid-75, .mobile-grid-80, .mobile-grid-85, .mobile-grid-90, .mobile-grid-95, .mobile-grid-100, .mobile-grid-33, .mobile-grid-66{ position: relative; box-sizing: border-box; flex: 0 0 auto; }.hide-on-mobile{ display: none !important; }.mobile-grid-5{ max-width: 5%; flex-basis: 5%; }.mobile-grid-10{ max-width: 10%; flex-basis: 10%; }.mobile-grid-15{ max-width: 15%; flex-basis: 15%; }.mobile-grid-20{ max-width: 20%; flex-basis: 20%; }.mobile-grid-25{ max-width: 25%; flex-basis: 25%; }.mobile-grid-30{ max-width: 30%; flex-basis: 30%; }.mobile-grid-35{ max-width: 35%; flex-basis: 35%; }.mobile-grid-40{ max-width: 40%; flex-basis: 40%; }.mobile-grid-45{ max-width: 45%; flex-basis: 45%; }.mobile-grid-50{ max-width: 50%; flex-basis: 50%; }.mobile-grid-55{ max-width: 55%; flex-basis: 55%; }.mobile-grid-60{ max-width: 60%; flex-basis: 60%; }.mobile-grid-65{ max-width: 65%; flex-basis: 65%; }.mobile-grid-70{ max-width: 70%; flex-basis: 70%; }.mobile-grid-75{ max-width: 75%; flex-basis: 75%; }.mobile-grid-80{ max-width: 80%; flex-basis: 80%; }.mobile-grid-85{ max-width: 85%; flex-basis: 85%; }.mobile-grid-90{ max-width: 90%; flex-basis: 90%; }.mobile-grid-95{ max-width: 95%; flex-basis: 95%; }.mobile-grid-33{ max-width: 33.33333%; flex-basis: 33.33333%; }.mobile-grid-66{ max-width: 66.66667%; flex-basis: 66.66667%; }.mobile-grid-100{ max-width: 100%; flex-basis: 100%; }.gm-navbar.gm-navbar--style-4 .gm-navbar-nav .gm-menu-item__icon{ margin-right: 8px; }.gm-toolbar-bg{ position: absolute; top: 0; left: 0; width: 100%; height: 100%; transition: opacity 0.2s; z-index: -1; }.gm-container{ padding-right: 15px; padding-left: 15px; flex-wrap: wrap; }.gm-main-menu-wrapper{ overflow-y: auto; padding-right: 15px; padding-left: 15px; justify-content: center; align-items: flex-start; flex-wrap: wrap; transform: translate3d(250px, 0, 0); position: fixed; right: 0; z-index: 1001; }#gm-main-menu{ position: relative; flex: 1 100%; }.gm-navbar-nav{ flex-direction: column; }.gm-navbar-nav > .gm-menu-item > a{ padding-top: 11px; padding-bottom: 11px; text-transform: uppercase; border-bottom-width: 1px; border-bottom-style: dotted; font-size: 11px; font-weight: 700; }.gm-dropdown-submenu .gm-caret{ transform: rotate(90deg); }[dir='rtl'] .gm-dropdown-submenu .gm-caret{ transform: rotate(-90deg); }.gm-navbar-nav > li{ flex-wrap: wrap; }.gm-actions{ align-self: flex-end; }.gm-actions > div:nth-of-type(n+2){ border-left-width: 1px; border-left-style: solid; }.gm-search{ min-width: 50%; margin-top: 50px; margin-bottom: 25px; padding-right: 20px; padding-left: 20px; text-align: center; flex-direction: column; flex-shrink: 0; cursor: pointer; }.gm-minicart{ display: flex; min-width: 50%; margin-top: 50px; margin-bottom: 25px; padding-right: 20px; padding-left: 20px; text-align: center; flex-shrink: 0; }#cart-counter{ top: -24px; right: -12px; }.gm-minicart-icon-wrapper{ display: flex; flex-direction: column; }.gm-minicart-icon-wrapper i, .gm-search > i{ display: block; line-height: 1; }.gm-minicart-icon-wrapper > .gm-minicart__txt{ margin-top: 8px }.attachment-menu-thumb{ display: none; }.gm-dropdown-menu, .gm-minicart-dropdown, .gm-minicart-dropdown{ display: none; }.is-open > .gm-dropdown-menu, .is-open > .gm-minicart-dropdown, .is-open > .gm-search-wrapper{ display: block; }.gm-dropdown-menu{ position: static; }.gm-dropdown-menu .gm-mega-menu__item{ padding-left: 15px; }.gm-dropdown-menu .gm-mega-menu__item .gm-menu-item{ padding-left: 15px; }.gm-dropdown-menu .gm-mega-menu__item__title{ padding-top: 12px; padding-bottom: 12px; }.gm-menu-item__link{ margin-right: 0; margin-left: 0; padding-right: 0; border-bottom: 1px dotted #bdbdbd; font-size: 11px; font-weight: 700; }.gm-dropdown-menu .gm-menu-item{ overflow: hidden; padding-right: 0; }.gm-navbar-offcanvas{ position: fixed; z-index: 1001; }.gm-navbar-offcanvas--left{ right: 0; left: auto }.gm-navbar-offcanvas--right{ left: 0; right: auto; }.gm-navbar--overlap .gm-wrapper{ position: absolute; }.gm-mega-menu__item__title{ text-transform: uppercase; border-bottom-color: #bdbdbd; font-size: 11px; font-weight: 700; }.gm-mega-menu-wrapper--background, .gm-dropdown-menu--background{ background-image: none !important; }.gm-menu-btn{ display: flex; }.gm-main-menu-wrapper.gm-mobile-skin--dark{ background-color: #222323; }.gm-main-menu-wrapper.gm-mobile-skin--dark .gm-navbar-nav > .gm-menu-item > a, .gm-main-menu-wrapper.gm-mobile-skin--dark .gm-menu-item__link{ border-bottom: 1px dotted #464848; }.gm-main-menu-wrapper.gm-mobile-skin--dark .gm-mega-menu__item__title{ color: #5a5a5a; }.gm-main-menu-wrapper.gm-mobile-skin--dark .menu-item > a{ color: #6e6e6f; }.gm-main-menu-wrapper.gm-mobile-skin--dark .gm-search__input{ height: 41px; background-color: #1f2020; box-shadow: 0.3px 0.9px 0 rgba(255, 255, 255, 0.03), inset 0.5px 0.9px 2px rgba(0, 0, 0, 0.15); }.gm-main-menu-wrapper.gm-mobile-skin--dark .gm-search-wrapper button{ background-color: transparent; }.gm-main-menu-wrapper.gm-mobile-skin--dark .gm-search-wrapper button:hover{ background-color: #a5e25e; }.gm-main-menu-wrapper.gm-mobile-skin--dark .gm-search-wrapper button:hover > i{ color: #fff; }.gm-main-menu-wrapper.gm-mobile-skin--dark .gm-navbar-nav a, .gm-main-menu-wrapper.gm-mobile-skin--dark .gm-search > i, .gm-main-menu-wrapper.gm-mobile-skin--dark .gm-search > .gm-search__txt, .gm-main-menu-wrapper.gm-mobile-skin--dark .gm-minicart-icon-wrapper > i, .gm-main-menu-wrapper.gm-mobile-skin--dark .gm-minicart-icon-wrapper > .gm-minicart__txt, .gm-main-menu-wrapper.gm-mobile-skin--dark .gm-actions > div:nth-of-type(n+2){ color: #6e6e6f; border-color: #6e6e6f; }.gm-main-menu-wrapper.gm-mobile-skin--light{ background-color: #fff; }.gm-main-menu-wrapper.gm-mobile-skin--light .gm-search-wrapper button:hover{ background-color: #a5e25e; }.gm-main-menu-wrapper.gm-mobile-skin--light .gm-search-wrapper button:hover > i{ color: #fff; }.gm-main-menu-wrapper.gm-mobile-skin--light .gm-navbar-nav .gm-dropdown-toggle, .gm-main-menu-wrapper.gm-mobile-skin--light .gm-navbar-nav .gm-menu-item__link, .gm-main-menu-wrapper.gm-mobile-skin--light .gm-search > i, .gm-main-menu-wrapper.gm-mobile-skin--light .gm-search > .gm-search__txt, .gm-main-menu-wrapper.gm-mobile-skin--light .gm-minicart-icon-wrapper > i, .gm-main-menu-wrapper.gm-mobile-skin--light .gm-minicart-icon-wrapper > .gm-minicart__txt, .gm-main-menu-wrapper.gm-mobile-skin--light .gm-actions > div:nth-of-type(n+2){ color: #5a5a5a; border-color: #5a5a5a; }.gm-navbar-animated{ transition: transform cubic-bezier(0.7, 0, 0.3, 1) 0.4s; }.groovy-nav-content-wrapper{ transition: transform cubic-bezier(0.7, 0, 0.3, 1) 0.4s; }.groovy-nav-is-open .gm-navbar-offcanvas{ transform: translate3d(0, 0, 0) !important; }}@media (min-width: 1023px) {.gm-navbar-nav > .gm-menu-item > a{ padding: 7px 15px; }}@media (min-width: 1023px) {.gm-navbar-nav > li > a{ transition: background-color 0.2s; }}@media (max-width: 1023px) {.gm-navbar-nav > .gm-menu-item > a{ padding: 7px 0; }}
</style>
<header class="gm-navbar gm-preset-id-106 gm-navbar--align-left gm-navbar--style-1 gm-top-links-align-right gm-navbar--toolbar-false gm-navbar--has-shadow-sticky gm-navbar--hide-gm-caret gm-dropdown-hover-style-shift-right gm-dropdown-appearance-animate-from-bottom" id="gm-5bcb706e4a1a1" data-version="1.3">
  <div class="gm-wrapper">
    <div class="gm-inner">
      <div class="gm-inner-bg"></div>
      <div class="gm-container">
        <div class="gm-logo"> <a href="index.html"><img src="wp-content/logo-wide.png" class="gm-logo__img gm-logo__img-alt" alt="" /><img src="wp-content/logo-wide.png" class="gm-logo__img gm-logo__img-sticky" alt="" /><img src="wp-content/uploads/2016/03/crane.svg" class="gm-logo__img gm-logo__img-mobile" alt="" /><img src="wp-content/uploads/2016/03/crane.svg" class="gm-logo__img gm-logo__img-sticky-mobile" alt="" /></a> </div>
        <span class="gm-menu-btn"> <span class="gm-menu-btn__inner"> <i class="fa fa-bars"></i> </span> </span>
        <div class="gm-main-menu-wrapper">
          <nav id="gm-main-menu">
							<ul id="menu-main-menu" class="gm-navbar-nav">
                            <li id="menu-item-1138" class="menu-item menu-item-type-custom menu-item-object-custom current-menu-ancestor current-menu-parent menu-item-has-children gm-menu-item gm-dropdown"><a href="#" class=" gm-dropdown-toggle"><span class="gm-menu-item__icon groovy-69018-home"></span><span class="gm-menu-item__txt">Home</span><span class="gm-caret"><i class="fa fa-fw fa-angle-down"></i></span></a>


</li>
<li id="menu-item-1141" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children gm-menu-item gm-dropdown mega-gm-dropdown"><a href="#" class=" gm-dropdown-toggle"><span class="gm-menu-item__icon groovy-69018-paper-plane"></span><span class="gm-menu-item__txt">About Us</span><span class="gm-caret"><i class="fa fa-fw fa-angle-down"></i></span></a>

</li>
<li id="menu-item-1142" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children gm-menu-item gm-dropdown"><a href="#" class=" gm-dropdown-toggle"><span class="gm-menu-item__icon groovy-69018-moustache"></span><span class="gm-menu-item__txt">Services</span><span class="gm-caret"><i class="fa fa-fw fa-angle-down"></i></span></a>
<ul class='gm-dropdown-menu gm-dropdown-menu--lvl-1' style=''>


	<li id="menu-item-5867" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="shop-home/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Residential Solar</span></a> </li>
    
	
	<li id="menu-item-1157" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="checkout/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Commercial Solar</span></a></li>
</ul>
</li>
<li id="menu-item-1140" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children gm-menu-item gm-dropdown">
<a href="#" class=" gm-dropdown-toggle">
<span class="gm-menu-item__icon groovy-69018-layers"></span>
<span class="gm-menu-item__txt">Solar System</span>
<span class="gm-caret"><i class="fa fa-fw fa-angle-down"></i></span>
</a>
<ul class='gm-dropdown-menu gm-dropdown-menu--lvl-1' style=''>
	
    
	<li id="menu-item-6416" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children gm-menu-item gm-dropdown gm-dropdown-submenu"><a href="#" class=" gm-dropdown-toggle gm-menu-item__link"><span class="gm-menu-item__txt">On Grid</span><span class="gm-caret"><i class="fa fa-fw fa-angle-right"></i></span></a>
    
	<ul class='gm-dropdown-menu gm-dropdown-menu--lvl-2' style=''>
		<li id="menu-item-6411" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children gm-menu-item gm-dropdown gm-dropdown-submenu"><a href="category/masonry-sidebar-2/index.html" class="gm-dropdown-toggle gm-menu-item__link"><span class="gm-menu-item__txt">Inverters</span><span class="gm-caret"><i class="fa fa-fw fa-angle-right"></i></span></a>
        
        <ul class='gm-dropdown-menu gm-dropdown-menu--lvl-2' style=''>
        
        
		<li id="menu-item-6411" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children gm-menu-item gm-dropdown gm-dropdown-submenu"><a href="aurora.php" class="gm-dropdown-toggle gm-menu-item__link"><span class="gm-menu-item__txt">Aurora Inverters</span><span class="gm-caret"><i class="fa fa-fw fa-angle-right"></i></span></a>
		
		<ul class='gm-dropdown-menu gm-dropdown-menu--lvl-2' style=''>
		<li id="menu-item-6072" class="menu-item menu-item-type-taxonomy menu-item-object-category gm-menu-item"><a href="string-inverters.php" class="gm-menu-item__link"><span class="gm-menu-item__txt">String-Inverters</span></a></li>
		</ul>
		
		
		</li>
		<li id="menu-item-6072" class="menu-item menu-item-type-taxonomy menu-item-object-category gm-menu-item"><a href="growatt.php" class="gm-menu-item__link"><span class="gm-menu-item__txt">Growatt Inverters</span></a></li>
  <li id="menu-item-6072" class="menu-item menu-item-type-taxonomy menu-item-object-category gm-menu-item"><a href="micro.php" class="gm-menu-item__link"><span class="gm-menu-item__txt">Micro Inverters</span></a></li> 
  
  <li id="menu-item-6072" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children gm-menu-item gm-dropdown gm-dropdown-submenu"><a href="sma.php" class="gm-dropdown-toggle gm-menu-item__link"><span class="gm-menu-item__txt">SMA Inverters</span><span class="gm-caret"><i class="fa fa-fw fa-angle-right"></i></span></a>
  
  
  <ul class='gm-dropdown-menu gm-dropdown-menu--lvl-2' style=''>
		<li id="menu-item-6072" class="menu-item menu-item-type-taxonomy menu-item-object-category gm-menu-item"><a href="without-transformer.php" class="gm-menu-item__link"><span class="gm-menu-item__txt">Without-Transformer</span></a></li>
		</ul>
  
  </li>
  
  
  <li id="menu-item-6072" class="menu-item menu-item-type-taxonomy menu-item-object-category gm-menu-item"><a href="solax.php" class="gm-menu-item__link"><span class="gm-menu-item__txt">Solax Inverters</span></a></li> <li id="menu-item-6072" class="menu-item menu-item-type-taxonomy menu-item-object-category gm-menu-item"><a href="sungrow.php" class="gm-menu-item__link"><span class="gm-menu-item__txt">Sungrow Inverters</span></a></li> 
  <!-- Zever submenu  -->
  <li id="menu-item-6072" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children gm-menu-item gm-dropdown gm-dropdown-submenu"><a href="category/masonry-sidebar-3/index.html" class="gm-dropdown-toggle gm-menu-item__link"><span class="gm-menu-item__txt">Zever Solar Inverters</span><span class="gm-caret"><i class="fa fa-fw fa-angle-right"></i></span></a>
  
   <ul class='gm-dropdown-menu gm-dropdown-menu--lvl-2' style=''>
        
        
		<li id="menu-item-6411" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children gm-menu-item"><a href="evershine-t1.php" class="gm-menu-item__link"><span class="gm-menu-item__txt">Evershine T1 Solar Inverters</span></a></li>
		<li id="menu-item-6072" class="menu-item menu-item-type-taxonomy menu-item-object-category gm-menu-item"><a href="evershine-tlc.php" class="gm-menu-item__link"><span class="gm-menu-item__txt">Evershine TLC Solar Inverters</span></a></li>
		
		 <li id="menu-item-6072" class="menu-item menu-item-type-taxonomy menu-item-object-category gm-menu-item"><a href="zeverlution-s.php" class="gm-menu-item__link"><span class="gm-menu-item__txt">Zeverlution S Solar Inverters</span></a></li>
		
        <li id="menu-item-6072" class="menu-item menu-item-type-taxonomy menu-item-object-category gm-menu-item"><a href="zeverlution.php" class="gm-menu-item__link"><span class="gm-menu-item__txt">Zeverlution Solar Inverters</span></a></li>
        </ul>
  
  
  
  
  </li>    
        
        
		
	</ul>
        
        
 
        </li>
		<li id="menu-item-6072" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children gm-menu-item gm-dropdown gm-dropdown-submenu"><a href="category/masonry-sidebar-3/index.html" class="gm-dropdown-toggle gm-menu-item__link"><span class="gm-menu-item__txt">Solar Panels</span><span class="gm-caret"><i class="fa fa-fw fa-angle-right"></i></span></a>
        
        
        
       <ul class='gm-dropdown-menu gm-dropdown-menu--lvl-2' style=''>
        
        
		<li id="menu-item-6411" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children gm-menu-item"><a href="canadian-solar.php" class="gm-menu-item__link"><span class="gm-menu-item__txt">Canadian Solar</span></a></li>
		
		<li id="menu-item-6411" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children gm-menu-item"><a href="gcl.php" class="gm-menu-item__link"><span class="gm-menu-item__txt">GCL</span></a></li>
		
  <li id="menu-item-6072" class="menu-item menu-item-type-taxonomy menu-item-object-category gm-menu-item"><a href="lg-panel.php" class="gm-menu-item__link"><span class="gm-menu-item__txt">LG Panel</span></a></li> <li id="menu-item-6072" class="menu-item menu-item-type-taxonomy menu-item-object-category gm-menu-item"><a href="q-cells.php" class="gm-menu-item__link"><span class="gm-menu-item__txt">Q-Cells</span></a></li>
  <li id="menu-item-6072" class="menu-item menu-item-type-taxonomy menu-item-object-category gm-menu-item"><a href="rec-solar-panel.php" class="gm-menu-item__link"><span class="gm-menu-item__txt">Rec Solar Panels</span></a></li> 
  
  <li id="menu-item-6072" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children gm-menu-item gm-dropdown gm-dropdown-submenu"><a href="category/masonry-sidebar-3/index.html" class="gm-dropdown-toggle gm-menu-item__link"><span class="gm-menu-item__txt">Sun Power</span><span class="gm-caret"><i class="fa fa-fw fa-angle-right"></i></span></a>
  
   <ul class='gm-dropdown-menu gm-dropdown-menu--lvl-2' style=''>
        
        
		<li id="menu-item-6411" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children gm-menu-item"><a href="e-series-solar-panels.php" class="gm-menu-item__link"><span class="gm-menu-item__txt">E-Series Solar Panels</span></a></li>
		<li id="menu-item-6072" class="menu-item menu-item-type-taxonomy menu-item-object-category gm-menu-item"><a href="x-series-solar-panels.php" class="gm-menu-item__link"><span class="gm-menu-item__txt">X-Series Solar Panels</span></a></li>
		
		 <li id="menu-item-6072" class="menu-item menu-item-type-taxonomy menu-item-object-category gm-menu-item"><a href="performance-series-solar-panels.php" class="gm-menu-item__link"><span class="gm-menu-item__txt">Performance Series Solar Panels</span></a></li>
		
       
        </ul>
  
  
  
  
  </li>     
  <li id="menu-item-6072" class="menu-item menu-item-type-taxonomy menu-item-object-category gm-menu-item"><a href="talesun.php" class="gm-menu-item__link"><span class="gm-menu-item__txt">Talesun</span></a></li>    
        
        
		
	</ul> 
        
        
        
        
        </li>
		
	</ul>
    </li>
    
    
    <li id="menu-item-6416" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children gm-menu-item gm-dropdown gm-dropdown-submenu"><a href="#" class=" gm-dropdown-toggle gm-menu-item__link"><span class="gm-menu-item__txt">Off Grid</span><span class="gm-caret"><i class="fa fa-fw fa-angle-right"></i></span></a>
	<ul class='gm-dropdown-menu gm-dropdown-menu--lvl-2' style=''>
		<li id="menu-item-6411" class="menu-item menu-item-type-taxonomy menu-item-object-category gm-menu-item"><a href="category/masonry-sidebar-2/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Masonry sidebar 2 columns</span></a></li>
		<li id="menu-item-6072" class="menu-item menu-item-type-taxonomy menu-item-object-category gm-menu-item"><a href="category/masonry-sidebar-3/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Masonry sidebar 3 columns</span></a></li>
		<li id="menu-item-6543" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="masonry-fullwidth-with-sidebar/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Masonry Fullwidth with Two Sidebars</span></a></li>
	</ul>
    
    
    
    
</ul>
</li>
<li id="menu-item-1139" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children gm-menu-item gm-dropdown mega-gm-dropdown"><a href="#" class=" gm-dropdown-toggle"><span class="gm-menu-item__icon groovy-69018-fire"></span><span class="gm-menu-item__txt">Career</span><span class="gm-caret"><i class="fa fa-fw fa-angle-down"></i></span></a>
<ul class='gm-dropdown-menu gm-dropdown-menu--lvl-1 gm-dropdown-menu--background' style='background-image: url(wp-content/uploads/2017/07/ba185a57c03f69bfbcd88d6e90abebde-optimized.jpg);background-repeat: no-repeat;background-position: center center;'>
<li><div style="" class="gm-mega-menu-wrapper"><div class="gm-grid-container"><div class="gm-grid-row"><div class="gm-mega-menu__item mobile-grid-100 grid-20"><div class="gm-mega-menu__item__title">Typography</div>
	<ul class='' style=''>
		<li id="menu-item-1848" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="headers-2/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Headings</span></a></li>
		<li id="menu-item-1868" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="custom-fonts/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Custom fonts</span></a></li>
		<li id="menu-item-1885" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="columns/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Columns</span></a></li>
		<li id="menu-item-1909" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="fancy-text/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Fancy text</span></a></li>
		<li id="menu-item-1913" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="buttons/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Buttons</span></a></li>
		<li id="menu-item-431" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="price-tables/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Price tables</span></a></li>
		<li id="menu-item-1949" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="flip-box/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Flip boxes</span></a></li>
		<li id="menu-item-1967" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="info-box/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Info box</span></a></li>
		<li id="menu-item-2364" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="list-icon/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">List icon</span></a></li>
	</ul>
</div><div class="gm-mega-menu__item mobile-grid-100 grid-20"><div class="gm-mega-menu__item__title">Common elements</div>
	<ul class='' style=''>
		<li id="menu-item-1941" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="counters/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Counters</span></a></li>
		<li id="menu-item-739" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="timeline/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Timeline</span></a></li>
		<li id="menu-item-2018" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="google-maps-trends/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Google maps &#038; trends</span></a></li>
		<li id="menu-item-2032" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="highlight-box/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Highlight box</span></a></li>
		<li id="menu-item-2054" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="info-banner/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Info banner</span></a></li>
		<li id="menu-item-2089" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="info-circle/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Info circle</span></a></li>
		<li id="menu-item-2119" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="modal-box/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Modal box</span></a></li>
		<li id="menu-item-2091" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="interactive-banners/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Interactive banners</span></a></li>
		<li id="menu-item-2180" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="creative-link/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Creative link</span></a></li>
	</ul>
</div><div class="gm-mega-menu__item mobile-grid-100 grid-20"><div class="gm-mega-menu__item__title">Interactive elements</div>
	<ul class='' style=''>
		<li id="menu-item-2191" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="hotspot/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Hotspot</span></a></li>
		<li id="menu-item-2207" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="tabs/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Tabs</span></a></li>
		<li id="menu-item-2216" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="row-separator/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Row separator</span></a></li>
		<li id="menu-item-2224" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="message-box/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Message box</span></a></li>
		<li id="menu-item-3528" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="accordion/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Accordion</span></a></li>
		<li id="menu-item-3529" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="charts/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Charts</span></a></li>
		<li id="menu-item-3530" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="media-grid-masonry/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Media grid &#038; masonry</span></a></li>
		<li id="menu-item-3531" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="countdown/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Countdown</span></a></li>
		<li id="menu-item-3532" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="hover-box/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Hover box</span></a></li>
	</ul>
</div><div class="gm-mega-menu__item mobile-grid-100 grid-20"><div class="gm-mega-menu__item__title">Interactive elements 2</div>
	<ul class='' style=''>
		<li id="menu-item-3534" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="parallax-background/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Parallax background</span></a></li>
		<li id="menu-item-3535" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="classic-carousel/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Classic carousel</span></a></li>
		<li id="menu-item-3536" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="video/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Video</span></a></li>
		<li id="menu-item-3537" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="progress-bar/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Progress bar</span></a></li>
		<li id="menu-item-3538" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="headers/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Headers</span></a></li>
		<li id="menu-item-3539" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="footers/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Footers</span></a></li>
	</ul>
</div><div class="gm-mega-menu__item mobile-grid-100 grid-20"><div class="gm-mega-menu__item__title">Groovy menu</div>
	<ul class='' style=''>
		<li id="menu-item-3627" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="standard-menu/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Standard menu</span></a></li>
		<li id="menu-item-3626" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="standart-menu-with-toolbar/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Standard menu with toolbar</span></a></li>
		<li id="menu-item-3625" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="standard-menu-transparent/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Standard menu transparent</span></a></li>
		<li id="menu-item-3624" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="centered-standard-menu/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Centered standard menu</span></a></li>
		<li id="menu-item-3657" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="minimalistic-menu/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Minimalistic menu</span></a></li>
		<li id="menu-item-3623" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="left-sidebar-menu/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Left sidebar menu</span></a></li>
		<li id="menu-item-3622" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="right-sidebar-menu/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Right sidebar menu</span></a></li>
		<li id="menu-item-3621" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="left-sidebar-icon-menu/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Left sidebar icon menu</span></a></li>
		<li id="menu-item-3743" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="right-sidebar-icon-menu/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Right sidebar icon menu</span></a></li>
		<li id="menu-item-3702" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="transparent-menu-with-border/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Transparent menu with border</span></a></li>
		<li id="menu-item-3708" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="transparent-light-sticky-dark/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Transparent light – sticky dark</span></a></li>
		<li id="menu-item-3715" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="standart-dark/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Standard dark</span></a></li>
	</ul>
</div></div></div></div></li></ul>
</li>
<li id="menu-item-3540" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children gm-menu-item gm-dropdown"><a href="#" class=" gm-dropdown-toggle"><span class="gm-menu-item__icon groovy-69018-notebook"></span><span class="gm-menu-item__txt">Contact Us</span><span class="gm-caret"><i class="fa fa-fw fa-angle-down"></i></span></a>
<ul class='gm-dropdown-menu gm-dropdown-menu--lvl-1' style=''>
	<li id="menu-item-6075" class="menu-item menu-item-type-taxonomy menu-item-object-category gm-menu-item"><a href="category/classic-blog/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Classic blog style</span></a></li>
	<li id="menu-item-6747" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="classic-blog-style-without-sidebar/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Classic blog without sidebar</span></a></li>
	<li id="menu-item-6415" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children gm-menu-item gm-dropdown gm-dropdown-submenu"><a href="#" class=" gm-dropdown-toggle gm-menu-item__link"><span class="gm-menu-item__txt">Masonry</span><span class="gm-caret"><i class="fa fa-fw fa-angle-right"></i></span></a>
	<ul class='gm-dropdown-menu gm-dropdown-menu--lvl-2' style=''>
		<li id="menu-item-6406" class="menu-item menu-item-type-taxonomy menu-item-object-category gm-menu-item"><a href="category/masonry-2/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Masonry 2 columns</span></a></li>
		<li id="menu-item-6407" class="menu-item menu-item-type-taxonomy menu-item-object-category gm-menu-item"><a href="category/masonry-3/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Masonry 3 columns</span></a></li>
		<li id="menu-item-6073" class="menu-item menu-item-type-taxonomy menu-item-object-category gm-menu-item"><a href="category/masonry-4/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Masonry 4 columns</span></a></li>
		<li id="menu-item-6777" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="masonry-5-columns/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Masonry 5 columns</span></a></li>
		<li id="menu-item-6550" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="masonry-fullwidth/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Masonry Fullwidth</span></a></li>
	</ul>
</li>
	<li id="menu-item-6416" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children gm-menu-item gm-dropdown gm-dropdown-submenu"><a href="#" class=" gm-dropdown-toggle gm-menu-item__link"><span class="gm-menu-item__txt">Masonry with sidebar</span><span class="gm-caret"><i class="fa fa-fw fa-angle-right"></i></span></a>
	<ul class='gm-dropdown-menu gm-dropdown-menu--lvl-2' style=''>
		<li id="menu-item-6411" class="menu-item menu-item-type-taxonomy menu-item-object-category gm-menu-item"><a href="category/masonry-sidebar-2/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Masonry sidebar 2 columns</span></a></li>
		<li id="menu-item-6072" class="menu-item menu-item-type-taxonomy menu-item-object-category gm-menu-item"><a href="category/masonry-sidebar-3/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Masonry sidebar 3 columns</span></a></li>
		<li id="menu-item-6543" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="masonry-fullwidth-with-sidebar/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Masonry Fullwidth with Two Sidebars</span></a></li>
	</ul>
</li>
	<li id="menu-item-6530" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children gm-menu-item gm-dropdown gm-dropdown-submenu"><a href="http://xn--m2g/" class=" gm-dropdown-toggle gm-menu-item__link"><span class="gm-menu-item__txt">Cell Style</span><span class="gm-caret"><i class="fa fa-fw fa-angle-right"></i></span></a>
	<ul class='gm-dropdown-menu gm-dropdown-menu--lvl-2' style=''>
		<li id="menu-item-6529" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="cell-fullwidth/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Cell Style Fullwidth</span></a></li>
		<li id="menu-item-6549" class="menu-item menu-item-type-post_type menu-item-object-page gm-menu-item"><a href="cell-style-with-sidebar/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Cell style with sidebar</span></a></li>
	</ul>
</li>
	<li id="menu-item-3545" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children gm-menu-item gm-dropdown gm-dropdown-submenu"><a href="#" class=" gm-dropdown-toggle gm-menu-item__link"><span class="gm-menu-item__txt">Single post</span><span class="gm-caret"><i class="fa fa-fw fa-angle-right"></i></span></a>
	<ul class='gm-dropdown-menu gm-dropdown-menu--lvl-2' style=''>
		<li id="menu-item-6514" class="menu-item menu-item-type-post_type menu-item-object-post gm-menu-item"><a href="2015/08/09/standart-post/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Standard post with sidebar</span></a></li>
		<li id="menu-item-6513" class="menu-item menu-item-type-post_type menu-item-object-post gm-menu-item"><a href="2015/05/25/post-visual-composer-modules/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Post with Visual composer modules</span></a></li>
		<li id="menu-item-6077" class="menu-item menu-item-type-post_type menu-item-object-post gm-menu-item"><a href="2017/03/06/post-with-a-link/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Post with a link</span></a></li>
		<li id="menu-item-6087" class="menu-item menu-item-type-post_type menu-item-object-post gm-menu-item"><a href="2015/06/23/post-with-quote/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Post with quote without image</span></a></li>
		<li id="menu-item-6078" class="menu-item menu-item-type-post_type menu-item-object-post gm-menu-item"><a href="2017/01/15/wordpress-audio-post/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">WordPress audio post</span></a></li>
		<li id="menu-item-6079" class="menu-item menu-item-type-post_type menu-item-object-post gm-menu-item"><a href="2017/01/15/wordpress-video-post/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">WordPress video post</span></a></li>
		<li id="menu-item-6080" class="menu-item menu-item-type-post_type menu-item-object-post gm-menu-item"><a href="2015/06/11/embeded-audio-post/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Embeded audio post</span></a></li>
		<li id="menu-item-6081" class="menu-item menu-item-type-post_type menu-item-object-post gm-menu-item"><a href="2015/05/17/embeded-video-post/index.html" class=" gm-menu-item__link"><span class="gm-menu-item__txt">Embeded video post</span></a></li>
	</ul>
</li>
</ul>
</li>
</ul>						</nav>
          <!--<div class="gm-actions">
															<span class="gm-nav-inline-divider"></span>
															
															
													
													
													
													
													
													</div>--> 
        </div>
        
        <!-- End Navigation Bar--> 
        
      </div>
    </div>
  </div>
  <div class="gm-padding"></div>
</header>
<div class="preloader"></div>
<div class="crane-content">
  <div class="post-1341 page type-page status-publish hentry">
    <div id="content">
      <div class="crane-section crane-parallax-fixed">
        <div class="crane-background" style="background-image: url('wp-content/aboutus_header.jpeg');background-position: center center;"></div>
        <div class="crane-background-overlay" style="background-color: rgba(0,0,0,0.4)"></div>
        <div class="crane-container">
          <div class="vc_row wpb_row vc_row-fluid">
            <div class="wpb_column vc_column_container vc_col-sm-12">
              <div class="vc_column-inner ">
                <div class="wpb_wrapper">
                  <div class="ult-spacer spacer-5bcb706e74d8a" data-id="5bcb706e74d8a" data-height="350" data-height-mobile="350" data-height-tab="350" data-height-tab-portrait="" data-height-mobile-landscape="" style="clear:both;display:block;"></div>
                  <div class="vc_separator wpb_content_element vc_separator_align_center vc_sep_width_100 vc_sep_pos_align_center vc_separator_no_text" ><span class="vc_sep_holder vc_sep_holder_l"><span  style="border-color:rgb(255,255,255);border-color:rgba(255,255,255,0.2);" class="vc_sep_line"></span></span><span class="vc_sep_holder vc_sep_holder_r"><span  style="border-color:rgb(255,255,255);border-color:rgba(255,255,255,0.2);" class="vc_sep_line"></span></span> </div>
                  <div id="ultimate-heading-17795bcb706e752b8" class="uvc-heading ult-adjust-bottom-margin ultimate-heading-17795bcb706e752b8 uvc-2494 " data-hspacer="no_spacer"  data-halign="left" style="text-align:left">
                    <div class="uvc-heading-spacer no_spacer" style="top"></div>
                    <div class="uvc-main-heading ult-responsive"  data-ultimate-target='.uvc-heading.ultimate-heading-17795bcb706e752b8 h2'  data-responsive-json-new='{"font-size":"desktop:46px;","line-height":"desktop:60px;"}' >
                      <h2 style="font-weight:bold;color:#ffffff;margin-top:60px;margin-bottom:60px;">About Us</h2>
                    </div>
                  </div>
                  <div class="ult-spacer spacer-5bcb706e75331" data-id="5bcb706e75331" data-height="20" data-height-mobile="20" data-height-tab="20" data-height-tab-portrait="" data-height-mobile-landscape="" style="clear:both;display:block;"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>      

